version: '3.7'

services:
  uscis_service:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8088 examples.db_server:main
    expose:
      - 8088
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    expose:
      - 80
    depends_on:
      - uscis_service

volumes:
  postgres_data:
