version: '3.7'

services:
  uscis_service:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: gunicorn examples.db_server:init_app --bind 0.0.0.0:5000 --worker-class aiohttp.worker.GunicornWebWorker
    expose:
      - 5000
    depends_on:
      - db
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
  uscis_service_dash:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: gunicorn examples.db_gui.app:server --bind 0.0.0.0:8050
    expose:
      - 8050
    depends_on:
      - db
      - uscis_service
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
  uscis_service_schedule:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: python -m examples.db_schedule
    depends_on:
      - db
      - uscis_service
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: uscis
    expose:
      - 5432
  nginx:
    build: ./nginx
    ports:
      - 1337:1337
      - 1338:1338
    depends_on:
      - db
      - uscis_service
      - uscis_service_schedule
      - uscis_service_dash

volumes:
  postgres_data:
