version: '3.7'

services:
  uscis_service:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: python examples.db_server
    expose:
      - 5000
    depends_on:
      - db
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: True
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: uscis
    expose:
      - 5432
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - uscis_service

volumes:
  postgres_data:
