version: '3.7'

services:
  uscis_service:
    build:
      context: ./uscis_service
      dockerfile: Dockerfile
    command: gunicorn  examples.db_server:init_app --bind 0.0.0.0:5000 --worker-class aiohttp.GunicornWebWorker
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: uscis
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - uscis_service

volumes:
  postgres_data:
